// 6日目通常パート（BAD END①ルート）
const scenesPart6_1 = [
    {
        name: '',
        text: '寝ている間、玄関の方から微かに昨日までと同じ声が聞こえてきた。',
        wifeFace: 'hidden',
        sonFace: 'hidden',
        background: 'entranceE',
        dayText: 'day',
    },
    {
        name: '',
        text: '意識がぼんやりとしていてあまり聞こえなかったが、',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '「薬」という言葉だけ、<br>はっきりと聞きとることができた。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '目が覚めた。時計を見るともう夕方のようだ。',
        wifeFace: 'hidden',
        sonFace: 'hidden',
        background: 'room',
        bgm: 'main',
    },
    {
        name: 'ゆみこ',
        text: '「おはよう。なかなか目を覚さないから心配したのよ。」',
        wifeFace: 'normal',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'どうやら昨日よりもさらに起きるのが遅かったらしい。<br>体が重い。お腹に強い痛みを感じる。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '今日も病気の具合が悪いようだ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「目が覚めたことだし、何か食べるものを用意してくるね！」',
        wifeFace: 'smile',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'いつも通りの会話の後、<br>ゆみこは料理を作りに、部屋を後にした。',
        wifeFace: 'hidden',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'ゆみこの顔が少し曇っていた。正直、心配だ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'しばらく時間が経った。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「ご飯できたよー」',
        wifeFace: 'normal',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'ゆみこが料理を持ってきてくれた。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'そういえば今日は何かが違う。ゆうただ！',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ねえ、今日ゆうたは？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「部屋にいるはずだけど、どうかした？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'よく考えれば毎日来る理由もない。<br>そんなに気にすることはないか。。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '「大丈夫、ちょっと気になっただけだから。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'そう言って、俺は料理を口にした。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「今日も最高に美味しいよ！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「あ、うん。ありがとう。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '食べ終わった。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '間違いない。薬の味だ。<br>でも一体何の薬だろう？なぜ俺に黙っているんだろう？',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'あまり考えたくはないな',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「あなた、おやすみなさい。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'そう言ってゆみこは部屋を後にした。',
        wifeFace: 'hidden',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '庭に、誘われなかった。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'やはりゆみこの様子が心配だ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'しかし、今の俺にできることはない。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '仕方ない、もう寝よう。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '俺はそのまま眠りについた。',
        wifeFace: 'stay',
        sonFace: 'stay',
        background: 'black',
        bgm: 'stop',
        nextScene: ['6_1', '7_1'],
    },
];
// 6日目隠しパート（END分岐）
const scenesPart6_2 = [
    {
        name: '',
        text: '寝ている間、玄関の方から微かに昨日までと同じ声が聞こえてきた。',
        wifeFace: 'hidden',
        sonFace: 'hidden',
        background: 'entranceE',
        dayText: 'day',
    },
    {
        name: '',
        text: '意識がぼんやりとしていてあまり聞こえなかったが、',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '「薬」という言葉だけ、<br>はっきりと聞きとることができた。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '目が覚めた。時計を見るともう夕方のようだ。',
        wifeFace: 'hidden',
        sonFace: 'hidden',
        background: 'room',
        bgm: 'main',
    },
    {
        name: 'ゆみこ',
        text: '「おはよう。なかなか目を覚さないから心配したのよ。」',
        wifeFace: 'normal',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'どうやら昨日よりもさらに起きるのが遅かったらしい。<br>体が重い。お腹に強い痛みを感じる。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '今日も病気の具合が悪いようだ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「目が覚めたことだし、何か食べるものを用意してくるね！」',
        wifeFace: 'smile',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'いつも通りの会話の後、<br>ゆみこは料理を作りに、部屋を後にした。',
        wifeFace: 'hidden',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'ゆみこの顔が少し曇っていた。正直、心配だ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'しばらくするとゆうたがやってきた。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「持ってきたよ！」',
        wifeFace: 'stay',
        sonFace: 'normal',
    },
    {
        name: '',
        text: '車椅子を運んできたようだ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「どうしたの？車椅子なんて持ってきて。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「だってほら！」',
        wifeFace: 'stay',
        sonFace: 'stay',
        mainFace: 'memo',
    },
    {
        name: '',
        text: 'ゆうたはメモを見せてきた。<br>ここ数日持ってきてもらったものが書いてある。',
        wifeFace: 'stay',
        sonFace: 'stay',
        mainFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「くるまいすって書いてあるから。」',
        wifeFace: 'stay',
        sonFace: 'stay',
        mainFace: 'stay',
    },
    {
        name: '',
        text: '驚いた。確かに縦読みしたら車椅子になっている。',
        wifeFace: 'stay',
        sonFace: 'stay',
        mainFace: 'stay',
    },
    {
        name: '',
        text: 'こんなことに気づくなんて、<br>ゆうたはきっと謎解きゲームにでもハマってるんだな。',
        wifeFace: 'stay',
        sonFace: 'stay',
        mainFace: 'stay',
    },
    {
        name: '',
        text: '偶然ではあるがせっかくだ。<br>車椅子を使わせてもらうことにしよう。',
        wifeFace: 'stay',
        sonFace: 'stay',
        mainFace: 'stay',
    },
    {
        name: '',
        text: 'ゆみこの様子も少し気になっていたところだし、<br>台所に向かってみるとするか。',
        wifeFace: 'stay',
        sonFace: 'stay',
        mainFace: 'stay',
    },
    {
        name: '',
        text: '俺は台所の方へ移動した。',
        wifeFace: 'hidden',
        sonFace: 'hidden',
        mainFace: 'hidden',
        wheel: 'yellow6',
        background: 'kitchen',
        bgm: 'stop',
    },
    {
        name: '',
        text: '台所ではゆみこが料理をしているようだ。',
        wifeFace: 'hidden',
        sonFace: 'hidden',
        bgm: 'serious'
    },
    {
        name: '',
        text: '隙間からそっと覗いてみる。',
        wifeFace: 'hidden',
        sonFace: 'hidden',
    },
    {
        name: '',
        text: 'あれは、、？',
        wifeFace: 'hidden',
        sonFace: 'hidden',
    },
    {
        name: '',
        text: '間違いない。粉状の薬を料理に入れている。',
        wifeFace: 'hidden',
        sonFace: 'hidden',
    },
    {
        name: '',
        text: '状況証拠から考えて、まず間違いなく体に良くない薬だろう。',
        wifeFace: 'hidden',
        sonFace: 'hidden',
    },
    {
        name: '',
        text: '何の薬なのか、何のために入れているのか、<br>なぜ俺に黙っているのか。何一つわからない。',
        wifeFace: 'hidden',
        sonFace: 'hidden',
    },
    {
        name: '',
        text: '一体、俺はどうするべきだろうか。',
        wifeFace: 'hidden',
        sonFace: 'hidden',
        choices: [  // 選択肢
            { text: '話しかける', nextScene: ['6_2', '6_2_2'] },
            { text: '見なかったことにする', nextScene: ['6_2', '6_2_1']  },
            { text: 'この家から逃げる', nextScene: ['6_2', '6_2_3']  },
        ],
    },
];