// 5日目部屋パート
const scenesPart5_1 = [
    {
        name: '',
        text: '寝ている間、玄関の方から微かに声が聞こえてきた。',
        wifeFace: 'hidden',
        sonFace: 'hidden',
        background: 'entranceE',
        dayText: 'day',
    },
    {
        name: '??',
        text: '「こちらも合わせればより大きな効果が得られるでしょう！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '一体何の話をしているんだろうか？',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '目が覚めた。時計を見るともう夕方のようだ。',
        wifeFace: 'hidden',
        sonFace: 'hidden',
        background: 'room',
        bgm: 'main',
    },
    {
        name: 'ゆみこ',
        text: '「おはよう。なかなか目を覚さないから心配したのよ。」',
        wifeFace: 'normal',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'どうやら昨日よりもさらに起きるのが遅かったらしい。<br>体が重い。お腹に強い痛みを感じる。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '今日も病気の具合が悪いようだ。<br>しかし、昨日に比べるとまだマシだ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「目が覚めたことだし、何か食べるものを用意してくるね！」',
        wifeFace: 'smile',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'いつも通りの会話の後、<br>ゆみこは料理を作りに、部屋を後にした。',
        wifeFace: 'hidden',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'ゆみこは本当に優しい。<br>まったく、良い嫁をもった。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「あ！！起きたんだ！」',
        wifeFace: 'stay',
        sonFace: 'normal',
    },
    {
        name: '',
        text: '息子のゆうたが部屋にやってきた。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「ねえねえ！何か欲しいものはある？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'メモ用紙と鉛筆を手に持っている。<br>どうやら頼んだものを持ってきてくれるようだ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'なんて優しい子なんだ！',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '不思議と最近ゆみこに似てきている。<br>成長期の子供は目を離した隙に別人になるってのは本当なんだな。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'さて、今日は果物があるってゆみこが言ってたな。<br>食事前だが誘惑には勝てない。何か持ってきてもらおう。',
        wifeFace: 'stay',
        sonFace: 'stay',
        choices: [  // 選択肢
            { text: 'メロン', nextScene: 1 },
            { text: 'すいか', nextScene: 1 },
            { text: 'いちご', nextScene: 1 },
        ],
    },
    {
        name: 'あなた',
        text: '「それじゃあ &nbsp ${lastChoiceText} &nbsp がほしいな！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「わかった！ &nbsp ${lastChoiceText} &nbsp だね！」<br>「間違えないようメモしておくね！」',
        wifeFace: 'stay',
        sonFace: 'smile',
    },
    {
        name: '',
        text: 'そう言って部屋を出た後、ゆうたはすぐに<br>${lastChoiceText} &nbsp を持って戻ってきてくれた。',
        wifeFace: 'stay',
        sonFace: 'normal',
    },
    {
        name: 'あなた',
        text: '「ありがとう！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「うん！じゃあまたね！」',
        wifeFace: 'stay',
        sonFace: 'smile',
    },
    {
        name: '',
        text: 'そう言ってゆうたは部屋を出ていった。<br>なんだか少し元気をもらえた気がする。',
        wifeFace: 'stay',
        sonFace: 'hidden',
    },
    {
        name: 'ゆみこ',
        text: '「ご飯できたよー」',
        wifeFace: 'normal',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'しばらくすると、ゆみこが料理を持ってきてくれた。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「今日も最高に美味しいよ！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「褒めすぎだってー」',
        wifeFace: 'smile',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「でも、ありがとう！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '食べ終わった。最高だ。<br>しかしまた薬っぽい味がした。味覚の問題なのか、それとも、、',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「ねえ、庭を見に行かない？」',
        wifeFace: 'normal',
        sonFace: 'stay',
    },
];
// 5日目庭パート
const scenesPart5_2 = [
    {
        name: '',
        text: 'ゆみこと俺は庭へ移動した。すると玄関には見慣れない石像があった。<br>これも新しく買ったのだろうか？',
        wifeFace: 'hidden',
        sonFace: 'stay',
        wheel: 'yellow5',
        background: 'tsubomi',
    },
    {
        name: '',
        text: 'この庭にはたくさんの思い出がある。<br>あれは何年前のことだったろう。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ゆみことケンカしたんだって？」',
        wifeFace: 'stay',
        sonFace: 'stay',
        background: 'sakura',
        bgm: 'past',
    },
    {
        name: 'ゆうた',
        text: '「うん。スマッシュシスターズのキャラ解放したいのに、<br>課金させてくれないんだよ。」',
        wifeFace: 'stay',
        sonFace: 'complain',
    },
    {
        name: 'あなた',
        text: '「うん、それでどうしたの？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「クソババアって言ったら、怒られて、」<br>「カーフキックして逃げてきた。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「なるほど、それはやっちゃったなー」<br>「ゆみこ相当痛がってたぞ？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「……」',
        wifeFace: 'stay',
        sonFace: 'normal',
    },
    {
        name: 'あなた',
        text: '「まあ課金させてくれないのは確かにクソだな。笑」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「でもなゆうた、よく聞いて。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ゆみこはゆうたのお母さんだから、<br>ちょっとくらいわがまま言ったっていい。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「でもそれ以前にな、ゆみこは俺の愛した人なんだ。<br>この世で一番、大切な人なんだ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「だから、ゆみこを言葉や暴力で傷つけるのはゆうたでも許せない。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「それに、ゆうたのことも同じくらい大切だから、<br>すごく悲しい気持ちになるんだよ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「……」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ゆうた、ちゃんとゆみこに謝れる？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「ごめんなさい。ちゃんと謝るよ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「よし、いい子だ！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '俺はゆうたの頭を優しく撫でた。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「じゃあゆうた、今日から俺と約束しよ！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「約束？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「この先ゆうたがどんな道を歩んでも俺は応援するよ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「どうしたの急に？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「この前ゆみこがさ、将来ゆうたは大学行って、<br>いい仕事についてほしいみたいなこと言ってだろ？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「そのために中学受験しようって言ってるけど、<br>ぶっちゃけあんまイメージわかなくね？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「いや、イメージわくよ？ &nbsp 僕勉強できるもん！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「え、そうなの？すげーな！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「でも勉強できるからって、<br>絶対大学行かなきゃいけないわけじゃないだろ？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「え、僕を堕落させたいの？」',
        wifeFace: 'stay',
        sonFace: 'complain',
    },
    {
        name: 'あなた',
        text: '「そんな難しい言葉いつ覚えたんだよ、、<br>でも待って違うから！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「俺はさ、中学受験も大学進学も、<br>自分で考えて決めるのが大事だと思うんだよ！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「勉強できるからとか、ゆみこに言われたからとかじゃなくて。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ゆうたの人生だからさ、ゆうたが本当にやりたいことを真剣に悩んで、<br>決めたらいいと思うんだ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「確かに盲目的に周りに流されて育ったら、<br>判断力のない無能な大人になっちゃうもんね。」',
        wifeFace: 'stay',
        sonFace: 'normal',
    },
    {
        name: 'あなた',
        text: '「え、きみ小学何年生？？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「さっきまでクソババアとか言ってた人だよね？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「子供の成長は速いんだよ！」',
        wifeFace: 'stay',
        sonFace: 'smile',
    },
    {
        name: 'あなた',
        text: '「いや、それで説明できるかー！」<br>「もうお前は東大へ行け！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「そのつもり」',
        wifeFace: 'stay',
        sonFace: 'normal',
    },
    {
        name: 'あなた',
        text: '「あ、そのつもりなの？」<br>「うちの子天才だったんだ。親なのに今まで知らなかったよ、、」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「それより、約束って？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「そうだ、本題に戻ろう！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「まあ俺は、ゆうたが決めたなら<br>どんな人生だろうと構わないと思ってるんだ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「流石に犯罪とかはダメだけど、不良になるくらいなら全然いいよ。<br>メビウス潰すのも応援する！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「でも、どんなに不良になったとしても、」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「どんなことがあっても、ゆみこのことだけはずっと大切にしてほしい。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「これが俺の唯一の願いなんだ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「約束、してくれるか？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「わかった。僕、お母さんのこと一生大切にするよ！<br>どんなことがあっても、必ず。」',
        wifeFace: 'stay',
        sonFace: 'resolve',
    },
    {
        name: 'ゆうた',
        text: '「不良にはならないけどね！」',
        wifeFace: 'stay',
        sonFace: 'normal',
    },
    {
        name: 'あなた',
        text: '「ゆうた、ありがとう！約束な！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '俺とゆうたは熱い抱擁を交わした。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「よし、じゃあスマシスの課金は後でこっそりしとくよ！<br>俺も勇者使いたいし！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「ほんと！？ありがとう！」',
        wifeFace: 'stay',
        sonFace: 'smile',
    },
    {
        name: 'あなた',
        text: '「その前に、まずはゆみこに謝りに行こう！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「うん」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'そんなこともあったな。',
        wifeFace: 'stay',
        sonFace: 'hidden',
        background: 'tsubomi',
        bgm: 'main',
    },
    {
        name: '',
        text: '子供の成長は本当に早い。<br>ゆうたが大人びていくのを見ると、嬉しくも寂しい気分になる。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'これが子育てってやつなのか。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'とはいえゆうたはまだ小学生。これから反抗期もきて、<br>厨二病になって、高校では青春して、',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'やっぱりグレる可能性もあるか。<br>それともオタクの道を極めたりするのかな？',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '約束したことだし、どんな道に進もうと、<br>ちゃんと応援してやらなきゃな。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'これからどんな風に成長していくのか、',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '本当に、楽しみだ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「……」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'ゆみこは少し疲れている様子だった。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ゆみこ、今日はもう戻ろう！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「あ、うん。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '俺は部屋に戻り、眠りについた。',
        wifeFace: 'hidden',
        sonFace: 'stay',
        background: 'black',
        bgm: 'stop',
        nextSceneAns: 32,
    },
];