// 1日目部屋パート
const scenesPart1_1 = [
    {
        name: '',
        text: '目が覚めた。時計を見るともう昼過ぎのようだ。',
        wifeFace: 'hidden',
        sonFace: 'hidden',
        dayText: 'day',
    },
    {
        name: '',
        text: '起きあがろうとすると、ベッドの脇にいた女性が手を貸してくれた。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「おはよう。なかなか目を覚さないから心配したのよ。」',
        wifeFace: 'normal',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'どうやら昨日よりも起きるのが遅かったらしい。<br>体が重い。お腹に痛みを感じる。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '病気の具合が悪化しているのだろうか？',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'しかし、医者には自宅療養で大丈夫と言われている。<br>もう少し様子を見ることにしよう。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「目が覚めたことだし、何か食べるものを用意してくるね！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「え、食欲ないからいらない？」<br>「側にいてほしい？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「もう、何言ってるのよ。」<br>「ただでさえずっと寝てるんだから、少しくらいは食べなきゃ元気でないよ。」',
        wifeFace: 'surprised',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「食べやすいものをすぐ作るから、少しだけ待ってて！」',
        wifeFace: 'smile',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'そう言い残すと、ゆみこは部屋を出ていった。',
        wifeFace: 'hidden',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '俺の嫁はとても優しい。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '思いやりがあって、真面目で純粋で、おまけに顔も良い、<br>男に言い寄られたことも多かっただろう。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'まったく、俺には勿体無いくらいだ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「あ！！起きたんだ！」',
        wifeFace: 'stay',
        sonFace: 'normal',
    },
    {
        name: '',
        text: '物思いに耽っていると息子のゆうたが部屋にやってきた。<br>現在小学5年生だが、春休みで学校はないらしい。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「ねえねえ！何か欲しいものはある？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'メモ用紙と鉛筆を手に持っている。<br>どうやら頼んだものを持ってきてくれるようだ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'なんて優しい子なんだ！',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '不思議と最近ゆみこに似てきている。<br>成長期の子供は目を離した隙に別人になるってのは本当なんだな。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'さて、もうすぐ春なのに、今日は少し肌寒い。<br>何か防寒できるものを持ってきてもらおう。',
        wifeFace: 'stay',
        sonFace: 'stay',
        choices: [  // 選択肢
            { text: 'くつした', nextScene: 1 },
            { text: 'てぶくろ', nextScene: 1 },
            { text: 'マフラー', nextScene: 1 },
        ],
    },
    {
        name: 'あなた',
        text: '「それじゃあ &nbsp ${lastChoiceText} &nbsp がほしいな！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「わかった！ &nbsp ${lastChoiceText} &nbsp だね！」<br>「間違えないようメモしておくね！」',
        wifeFace: 'stay',
        sonFace: 'smile',
    },
    {
        name: '',
        text: 'そう言って部屋を出た後、ゆうたはすぐに<br>${lastChoiceText} &nbsp を持って戻ってきてくれた。',
        wifeFace: 'stay',
        sonFace: 'normal',
    },
    {
        name: 'あなた',
        text: '「ありがとう！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「うん！じゃあまたね！」',
        wifeFace: 'stay',
        sonFace: 'smile',
    },
    {
        name: '',
        text: 'そう言ってゆうたは部屋を出ていった。<br>なんだか少し元気をもらえた気がした。',
        wifeFace: 'stay',
        sonFace: 'hidden',
    },
    {
        name: 'ゆみこ',
        text: '「ご飯できたよー」',
        wifeFace: 'normal',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'しばらくすると、ゆみこが料理を持ってきてくれた。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「今日も最高に美味しいよ！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「褒めすぎだってー」',
        wifeFace: 'smile',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「でも、ありがとう！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '食べ終わった。最高だ。<br>しかし今日はいつもより薄味だったな。体を気を遣ってくれたのだろう。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「ねえ、庭を見に行かない？」',
        wifeFace: 'normal',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '食後にするいつもの日課だ。<br>一人であまり動けない俺のために、車椅子で庭まで連れて行ってくれる。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
];
// 1日目庭パート
const scenesPart1_2 = [
    {
        name: '',
        text: 'ゆみこと俺は庭へ移動した。',
        wifeFace: 'hidden',
        sonFace: 'stay',
        wheel: 'yellow1',
        background: 'tsubomi',
    },
    {
        name: '',
        text: '庭の中央には桜の木がある。<br>もうすぐ開花の季節、またみんなでお花見するのが楽しみだ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'この庭にはたくさんの思い出がある。<br>あれは何年前のことだったろう。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ねえ、ゆみこ、結婚記念に木を植えない？」',
        wifeFace: 'stay',
        sonFace: 'stay',
        background: 'notree'
    },
    {
        name: 'ゆみこ',
        text: '「え、いいね！何の木にする？キャッサバ？」',
        wifeFace: 'youngN',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「タピオカ作る気？あれは店で買うからいいんだよ！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「じゃあヤクスギとか？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ゆみこ花粉症じゃん。てかなんで屋久島？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「じゃあガジュマルにする？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ちょっと一旦、熱帯から離れよっか？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「桜の木を植えようと思うんだ！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「桜！？素敵ね！桜って植えてから何年くらいで咲くの？」',
        wifeFace: 'youngS',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「5年から10年らしいよー。そんなに経ったら老けちゃうね。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「大袈裟でしょー」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「でも、2人でいつまでも一緒にいたいな。」',
        wifeFace: 'youngN',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「うん///」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「顔赤いね！大丈夫？」',
        wifeFace: 'normal',
        sonFace: 'stay',
        background: 'tsubomi'
    },
    {
        name: 'あなた',
        text: '「大丈夫！ただ昔のことを思い出してただけだよ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「えー、じゃあなんで顔赤いのー？」',
        wifeFace: 'smile',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'しばらく庭で談笑した後、俺は部屋に戻り、眠りについた。',
        wifeFace: 'hidden',
        sonFace: 'stay',
        background: 'black',
    },
];