// 3日目部屋パート
const scenesPart3_1 = [
    {
        name: '',
        text: '寝ている間、微かに玄関の方から話し声が聞こえた。<br>何かを買っているようだ。',
        wifeFace: 'hidden',
        sonFace: 'hidden',
        background: 'entranceE',
        dayText: 'day',
    },
    {
        name: '',
        text: '目が覚めた。時計を見るともう昼過ぎのようだ。',
        wifeFace: 'hidden',
        sonFace: 'hidden',
        background: 'room',
        bgm: 'main',
    },
    {
        name: 'ゆみこ',
        text: '「おはよう。なかなか目を覚さないから心配したのよ。」',
        wifeFace: 'normal',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'どうやら昨日よりもさらに起きるのが遅かったらしい。<br>体が重い。お腹に痛みを感じる。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '病気の具合が悪化しているのだろうか？',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'しかし、医者には自宅療養で大丈夫と言われている。<br>もう少し様子を見ることにしよう。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「目が覚めたことだし、何か食べるものを用意してくるね！」',
        wifeFace: 'smile',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'いつも通りの会話の後、<br>ゆみこは料理を作りに、部屋を後にした。',
        wifeFace: 'hidden',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'ゆみこは本当に優しい。<br>まったく、良い嫁をもった。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「あ！！起きたんだ！」',
        wifeFace: 'stay',
        sonFace: 'normal',
    },
    {
        name: '',
        text: '息子のゆうたが部屋にやってきた。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「ねえねえ！何か欲しいものはある？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'メモ用紙と鉛筆を手に持っている。<br>どうやら頼んだものを持ってきてくれるようだ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'なんて優しい子なんだ！',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '不思議と最近ゆみこに似てきている。<br>成長期の子供は目を離した隙に別人になるってのは本当なんだな。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'さて、今日は久しぶりにゲームでもしたいな<br>どのソフトを持ってきてもらおうか。',
        wifeFace: 'stay',
        sonFace: 'stay',
        choices: [  // 選択肢
            { text: 'マインクリエイティブ', nextScene: 1 },
            { text: 'モンスターハンティング', nextScene: 1 },
            { text: 'スマッシュシスターズ', nextScene: 1 },
        ],
    },
    {
        name: 'あなた',
        text: '「それじゃあ &nbsp ${lastChoiceText} &nbsp がほしいな！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「わかった！ &nbsp ${lastChoiceText} &nbsp だね！」<br>「間違えないようメモしておくね！」',
        wifeFace: 'stay',
        sonFace: 'smile',
    },
    {
        name: '',
        text: 'そう言って部屋を出た後、ゆうたはすぐに<br>${lastChoiceText} &nbsp を持って戻ってきてくれた。',
        wifeFace: 'stay',
        sonFace: 'normal',
    },
    {
        name: 'あなた',
        text: '「ありがとう！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「うん！じゃあまたね！」',
        wifeFace: 'stay',
        sonFace: 'smile',
    },
    {
        name: '',
        text: 'そう言ってゆうたは部屋を出ていった。<br>なんだか少し元気をもらえた気がする。',
        wifeFace: 'stay',
        sonFace: 'hidden',
    },
    {
        name: 'ゆみこ',
        text: '「ご飯できたよー」',
        wifeFace: 'normal',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'しばらくすると、ゆみこが料理を持ってきてくれた。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「今日も最高に美味しいよ！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「褒めすぎだってー」',
        wifeFace: 'smile',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「でも、ありがとう！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '食べ終わった。最高だ。<br>しかしなんだか少し薬っぽいような味がした気がする。<br>病気の影響が味覚にも出ているのだろうか。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「ねえ、庭を見に行かない？」',
        wifeFace: 'normal',
        sonFace: 'stay',
    },
];
// 3日目庭パート
const scenesPart3_2 = [
    {
        name: '',
        text: 'ゆみこと俺は庭へ移動した。',
        wifeFace: 'hidden',
        sonFace: 'stay',
        wheel: 'yellow2',
        background: 'tsubomi',
    },
    {
        name: '',
        text: 'この庭にはたくさんの思い出がある。<br>あれは何年前のことだったろう。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「ねえ見てー、さくらが満開になってる」',
        wifeFace: 'smile',
        sonFace: 'stay',
        background: 'sakura',
        bgm: 'past',
    },
    {
        name: 'ゆうた',
        text: '「すごい！すごい！こんなの初めてだー」',
        wifeFace: 'hidden',
        sonFace: 'smile',
    },
    {
        name: 'あなた',
        text: '「綺麗だなー」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「あなたがプロポーズしてくれた場所も、こんな桜の木だったよね。」',
        wifeFace: 'normal',
        sonFace: 'hidden',
    },
    {
        name: '',
        text: 'そういえばそうだった。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'ゆみこが好きな桜の木の下をわざわざ選んだったな。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「そうだったかなー？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「昔のことすぎて忘れちゃったなー」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「えー覚えてないの？」',
        wifeFace: 'surprised',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「あんなロマンチックだったのにー」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「あの日、手紙で桜の木の下に私を呼び出して、<br>目の前で片膝をついて指輪を、、」',
        wifeFace: 'smile',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「あー、言わなくて大丈夫！ちゃんと覚えてるから。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ちょっと恥ずかしくて誤魔化しただけだから！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「なーんだ、ならよかった」',
        wifeFace: 'normal',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「ゆうたももし告白する時はこれくらいロマンチックだと、<br>された方は嬉しいと思うよー」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「やだよ！そんな恥ずかしいこと死んでもできない！」',
        wifeFace: 'hidden',
        sonFace: 'complain',
    },
    {
        name: 'あなた',
        text: '「おい、やった人の前で言うなよ！」',
        wifeFace: 'hidden',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「うふふ」',
        wifeFace: 'smile',
        sonFace: 'hidden',
    },
    {
        name: 'ゆみこ',
        text: '「なんか照れてる？」',
        wifeFace: 'normal',
        sonFace: 'stay',
        background: 'tsubomi',
        bgm: 'main',
    },
    {
        name: 'あなた',
        text: '「そんなことないよー」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'しばらく庭で談笑した後、俺は部屋に戻り、眠りについた。',
        wifeFace: 'hidden',
        sonFace: 'stay',
        background: 'black',
        bgm: 'stop',
    },
];