// 6日目自白パート（HAPPY ENDルート）
const scenesPart6_2_1 = [
    {
        name: '',
        text: 'そうだ、見なかったことにしよう。',
        wifeFace: 'hidden',
        sonFace: 'hidden',
    },
    {
        name: '',
        text: 'ゆみこはこれまで散々俺に尽くしてくれた。<br>そんなゆみこを疑うなんて、俺にはできない。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'そう、俺は何も見なかった。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '部屋に戻って、ゆみこの料理を待とう。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'いつも通りご飯を食べて、いつも通りの会話をして、',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'いつも通り庭に行って、いつも通り眠って、<br>またゆみこに起こしてもらって、',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'そうやっていつも通りの日々を続けていこう。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '病気もきっとそのうち良くなる。<br>そしたらたくさん、ゆみこに恩返しをしよう。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'そんなことを考えながら、俺は部屋に戻った。',
        wifeFace: 'stay',
        sonFace: 'stay',
        background: 'room',
        bgm: 'main',
    },
    {
        name: 'ゆみこ',
        text: '「ご飯できたよー」',
        wifeFace: 'normal',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'ゆみこが料理を持ってきてくれた。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ゆみこ、いつもありがとう！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '俺は料理を口にした。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'すると、ゆみこは泣き出してしまった。',
        wifeFace: 'cry',
        sonFace: 'stay',
        bgm: 'ending',
    },
    {
        name: 'ゆみこ',
        text: '「ううっ…」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「どうして、、食べるの？」<br>「さっき薬入れてるの見てたんでしょ？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「うん。でも食べるよ。」<br>「せっかくゆみこが作ってくれたんだ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「ううっ……ごめん…なさい…」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'ゆみこは余計に泣いてしまった。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「これ以上嘘はつけないわ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'ゆみこは泣きながらも、ゆっくりと何かを話そうとしてくれている。<br>俺はゆみこの背中を優しくさすった。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「実はね、あなた、、末期の癌なの。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「自宅療養で治るっていうのは嘘で、」<br>「本当は、余命1週間だって、お医者さんが…」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '診断を受けてからもう6日目になる。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'そうか、もう死が近かったのか。<br>どうりで容体が悪化する一方なわけだ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「最期の1週間は病院より、家で過ごす方がいいって思って…」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「前にあなたがそう言ってたから…」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '確かに言ったかもしれない。<br>あれは確か数年前、今の俺と似たような状況の映画を見たときだ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「映画面白かったなー」',
        wifeFace: 'hidden',
        sonFace: 'stay',
        background: 'nae',
        bgm: 'past',
    },
    {
        name: 'ゆみこ',
        text: '「ううっ」',
        wifeFace: 'youngC',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '「それにしても、感情移入しすぎでしょ笑」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「だってー…ｸﾞｽﾝ」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「じゃあもしも、俺が余命宣告されたらどうする？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「うぇー、そんなの辛すぎるよー」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ああ、もっと泣いちゃった笑」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「まあでも、俺は何も知らずに普段通り過ごして、最期を迎えたいな」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「そうなの？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「うん、だって人生の最期は幸せでいたいじゃん？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「まあ俺にとって一番の幸せは、<br>ゆみこと一緒にいられる普段通りの日常なんだけどね。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「何それ？カッコつけちゃってー！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「でも、そっか、あなたらしいね！」',
        wifeFace: 'youngS',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「あのときのことを覚えてて、その通りにするとか、真面目か！笑」',
        wifeFace: 'cry',
        sonFace: 'stay',
        background: 'room',
        bgm: 'ending',
    },
    {
        name: 'ゆみこ',
        text: '「ううっ…ｸﾞｽﾝ」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'でも本当に俺のことを考えてくれてたんだな。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「そっかー、俺もう死ぬのかー」<br>「実感わかねー笑」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '俺の冗談をスルーし、ゆみこは話を続けた。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「だから、最期の1週間、笑顔でいてほしいって思って…」<br>「病気のこと、あなたには黙っておくって決めてたのに…」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「うん」（静かに頷く）',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「でもいざ看病してるとすごくつらくて…」<br>「あなたが亡くなるなんて信じたくなくて…」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「耐えられなくて…」<br>「何かにすがりたくて…」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「さっきの薬はね、分裂教会の人からもらって、<br>ちょっとずつ食事に入れてたの。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ああー笑、なるほど。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「医学でどうにもできないんだったら、<br>もう神を信じるしかないって言われて…」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「言われて？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「確かにそうかもって思って…」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「あちゃー」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「ううっ…ごめんなさい…」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'でもそっか、ゆみこは俺に病気のこと隠して、<br>一人で抱え込んじゃってたんだよな。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「つらかったよね。気づけなくてごめん。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '俺はそう言って、ゆみこをそっと抱きしめた。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'この6日間、ゆみこはきっと<br>俺の知らないところでたくさん葛藤してたんだろう。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '俺のために辛い気持ちを必死にこらえて、<br>できる限り明るく振る舞ってくれていたんだろう。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '数年前に一度話しただけのことをその通りにやろうとするところとか、<br>追い込まれて宗教にハマっちゃうところとか、',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '不器用なところも多いけど、なんと言うか、ゆみこらしい。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '思いやりがあって、真面目で純粋、おまけに顔も良い、<br>男に言い寄られることも多かっただろう。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'それでも俺のことを、こんなにも思ってくれて、',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'こんなにも、愛してくれて。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'まったく俺には勿体無い嫁を持ったな。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ゆみこ、愛してる。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'その後、ゆみこが泣き止むの待ってから、<br>残った料理を食べ切って、俺は深い眠りについた。',
        wifeFace: 'hidden',
        sonFace: 'stay',
        background: 'black',
        bgm: 'stop',
        nextScene: ['6_2_1', '7_2'],
    },
];
// 6日目火事パート（BAD END②ルート）
const scenesPart6_2_2 = [
    {
        name: 'あなた',
        text: '「ゆみこ、何してるの？」',
        wifeFace: 'hidden',
        sonFace: 'hidden',
    },
    {
        name: 'ゆみこ',
        text: '「あなた、どうして？」<br>「えっと、これは、その、、」',
        wifeFace: 'rushing',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '間違いない。この反応は、黒だ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ゆみこ、その薬を渡して！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「これは、、ダメなの。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「どうして？」<br>「なんのためにこんなこと、、」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「違うの、これは、、でも、、だって、、、」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'ゆみこは動揺している。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '最近のゆみこはどうも様子がおかしかった。<br>力づくでも薬を奪った方がいいだろう。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「とにかく、その薬を渡すんだ！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '俺は薬を取ろうと、車椅子から立ち上がりゆみこの方に向かった。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'が、歩けない。<br>自分の体力の衰えを侮っていた俺は、大きくバランスを崩した。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'そのまま棚に強く衝突し、その場に倒れた。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「ご、ごめんなさい。これはもう捨てるわ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ゆみこ待って！落ち着いて！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '俺の制止を聞かず、ゆみこは薬をコンロに焚べ、<br>次の瞬間、爆発した。',
        wifeFace: 'stay',
        sonFace: 'stay',
        bgm: 'stop',
    },
    {
        name: '',
        text: '急な出来事で理解が追いつかない。一体何が？',
        wifeFace: 'hidden',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'あたりを見渡すとコンロの火が家中に燃え広がっていた。<br>どうやら薬が引火性のものだったようだ。',
        wifeFace: 'stay',
        sonFace: 'stay',
        background: 'kitchenF',
        bgm: 'fire',
    },
    {
        name: '',
        text: '前方にゆみこが倒れている。<br>が、近づこうとしても動けない。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '俺は棚の下敷きになっていた。<br>これでは動けそうもない。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ゆみこー！ゆみこー！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '大声を出すがゆみこは気づかない。<br>意識を失っているようだ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'ああ、どうしてこんなことに。<br>俺はこんなこと望んでいなかった。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '俺はもう動けないが、<br>せめてゆみこだけでも助かってほしい。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '「ゆみこー！ゆみこー！ゆみこー！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'すると、ゆみこの顔がゆっくりとこっちを向いた。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'だが体が動く気配はない。動けないのだろうか。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '口が動いた。<br>ゆみこは泣きながら辛そうな表情で何か言っている。',
        wifeFace: 'cry',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '聞こえない。確かにゆみこの口は動いている。<br>だが聞こえない。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'ただ耳鳴りがするだけで、本当に何も聞こえない。家が燃える音さえも。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'ああそうか、爆発で鼓膜が破れたんだ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ゆみこ、ごめんな」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '俺にはそれしか言えなかった。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'ことの真相はわからない。<br>薬は一体なんだったのか。ゆみこは何をしようとしていたのか。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'だが、明らかにゆみこの様子に違和感はあった。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'もしかすると、どこかで俺がゆみこを追い詰めていたんじゃないだろうか。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'もっと早くゆみこと対話すべきだったのかもしれない。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'でももう遅い。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ゆみこ、ごめんな」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'ゆみこはまだ口を動かして何か言っているようだった。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'ああ、最後に、ゆみこの声、聞きたかったな。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '徐々に酸素が薄くなり、俺の意識はそこで途絶えた。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '',
        wifeFace: 'stay',
        sonFace: 'stay',
        background: 'roomF'
        
    },
    {
        name: '',
        text: '家が燃えた。',
        wifeFace: 'stay',
        sonFace: 'stay',
        background: 'black'
    },
    {
        name: '',
        text: '救出されたのは僕一人らしい。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「お母さん、、」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '',
        wifeFace: 'stay',
        sonFace: 'stay',
        background: 'endB2',
        end: 'BAD END②<br>「炎の中へ消えた真相」'
    },
];