// 2日目部屋パート
const scenesPart2_1 = [
    {
        name: '',
        text: '寝ている間、玄関の方で誰かが何か話しているような気がした。',
        wifeFace: 'hidden',
        sonFace: 'hidden',
        dayText: 'day',

    },
    {
        name: '',
        text: '目が覚めた。時計を見るともう昼過ぎのようだ。',
        wifeFace: 'hidden',
        sonFace: 'hidden',
        background: 'room',
        bgm: 'main',
    },
    {
        name: 'ゆみこ',
        text: '「おはよう。なかなか目を覚さないから心配したのよ。」',
        wifeFace: 'normal',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'どうやら昨日よりもさらに起きるのが遅かったらしい。<br>体が重い。お腹に痛みを感じる。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '病気の具合が悪化しているのだろうか？',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'しかし、医者には自宅療養で大丈夫と言われている。<br>もう少し様子を見ることにしよう。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「目が覚めたことだし、何か食べるものを用意してくるね！」',
        wifeFace: 'smile',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'いつも通りの会話の後、<br>ゆみこは料理を作りに、部屋を後にした。',
        wifeFace: 'hidden',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'ゆみこは本当に優しい。<br>まったく、良い嫁をもった。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「あ！！起きたんだ！」',
        wifeFace: 'stay',
        sonFace: 'normal',
    },
    {
        name: '',
        text: '息子のゆうたが部屋にやってきた。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「ねえねえ！何か欲しいものはある？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'メモ用紙と鉛筆を手に持っている。<br>どうやら頼んだものを持ってきてくれるようだ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'なんて優しい子なんだ！',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '不思議と最近ゆみこに似てきている。<br>成長期の子供は目を離した隙に別人になるってのは本当なんだな。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'さて、今日は甘いものが食べたい気分だ。<br>何かお菓子を持ってきてもらおう。',
        wifeFace: 'stay',
        sonFace: 'stay',
        choices: [  // 選択肢
            { text: 'カントリーマーチ', nextScene: 1 },
            { text: 'コアラのマーム', nextScene: 1 },
            { text: 'ルマンダ', nextScene: 1 },
        ],
    },
    {
        name: 'あなた',
        text: '「それじゃあ &nbsp ${lastChoiceText} &nbsp がほしいな！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「わかった！ &nbsp ${lastChoiceText} &nbsp だね！」<br>「間違えないようメモしておくね！」',
        wifeFace: 'stay',
        sonFace: 'smile',
    },
    {
        name: '',
        text: 'そう言って部屋を出た後、ゆうたはすぐに<br>${lastChoiceText} &nbsp を持って戻ってきてくれた。',
        wifeFace: 'stay',
        sonFace: 'normal',
    },
    {
        name: 'あなた',
        text: '「ありがとう！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「うん！じゃあまたね！」',
        wifeFace: 'stay',
        sonFace: 'smile',
    },
    {
        name: '',
        text: 'そう言ってゆうたは部屋を出ていった。<br>なんだか少し元気をもらえた気がした。',
        wifeFace: 'stay',
        sonFace: 'hidden',
    },
    {
        name: 'ゆみこ',
        text: '「ご飯できたよー」',
        wifeFace: 'normal',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'しばらくすると、ゆみこが料理を持ってきてくれた。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「今日も最高に美味しいよ！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「褒めすぎだってー」',
        wifeFace: 'smile',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「でも、ありがとう！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '食べ終わった。最高だ。<br>しかし今日は微かに馴染みのない味がした。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「ねえ、庭を見に行かない？」',
        wifeFace: 'normal',
        sonFace: 'stay',
    },
];
// 2日目庭パート
const scenesPart2_2 = [
    {
        name: '',
        text: 'ゆみこと俺は庭へ移動した。',
        wifeFace: 'hidden',
        sonFace: 'stay',
        wheel: 'yellow2',
        background: 'tsubomi',
    },
    {
        name: '',
        text: 'この庭にはたくさんの思い出がある。<br>あれは何年前のことだったろう。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ゆうた、これ何かわかる？」',
        wifeFace: 'stay',
        sonFace: 'stay',
        background: 'nae',
        bgm: 'past',
    },
    {
        name: 'ゆうた',
        text: '「さくらだっけ？」',
        wifeFace: 'stay',
        sonFace: 'youngN',
    },
    {
        name: 'あなた',
        text: '「そう！あと何年かしたら綺麗なピンクの花が咲くんだよ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「うそだー、だってみどりじゃん」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ほんと！これから大きくなってつぼみが出てくるんだよ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「そうなんだ！たのしみ！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ところで、この前保育園でケンカして泣かされたんだって？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「う、うん」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「好きな子守るために立ち向かったって聞いたけど、」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「それで負けたんだってー？ｸｽｸｽ」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「だっせー爆笑」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「うるさいよー」',
        wifeFace: 'stay',
        sonFace: 'youngA',
    },
    {
        name: 'あなた',
        text: '「でも立ち向かったのは偉いな！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「ケンカはダメって言わないの？」',
        wifeFace: 'stay',
        sonFace: 'youngN',
    },
    {
        name: 'あなた',
        text: '「俺だってゆみこのためならケンカするし、<br>逆にそこで何もできないやつの方がダメだな。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「でも笑、負けてるから結局なんもできてないのか。ﾌﾟﾌﾟﾌﾟ」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「もう、しつこいって」',
        wifeFace: 'stay',
        sonFace: 'youngA',
    },
    {
        name: 'あなた',
        text: '「まあ暴力は最終手段にとっておくのが理想だけど、<br>子供のうちはたくさんケンカしたらいいさ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「負けたっていいから、好きな子を守りたいって気持ちは大事にするんだよ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「うん」',
        wifeFace: 'stay',
        sonFace: 'youngN',
    },
    {
        name: 'あなた',
        text: '「実はこの桜ね、ゆみこが大切にしてきたおかげで、<br>台風にも大雪にも負けずにここまで育ったんだ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「けどさ、ゆみこはゆうたのこと、<br>桜よりずっと大切に育ててるんだよ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「だから大丈夫！ゆうたはきっと強い子になれるよ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「うん！ぼく、がんばる！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「桜が咲くのと、ゆうたがケンカに勝てるようになるの、<br>どっちが先になるかな？笑」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「もう、バカにしすぎだってー」',
        wifeFace: 'stay',
        sonFace: 'youngA',
    },
    {
        name: 'ゆみこ',
        text: '「なんか嬉しそうだね！」',
        wifeFace: 'normal',
        sonFace: 'hidden',
        background: 'tsubomi',
        bgm: 'main',
    },
    {
        name: 'あなた',
        text: '「ちょっと昔のこと思い出してたんだ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「えー、また？」',
        wifeFace: 'smile',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ゆうたがケンカで泣かされて帰ってきた時あっただろ？その時にさ、、、」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'しばらく庭で談笑した後、俺は部屋に戻り、眠りについた。',
        wifeFace: 'hidden',
        sonFace: 'stay',
        background: 'black',
        bgm: 'stop',
    },
];