// 4日目部屋パート
export const scenesPart4_1 = [
    {
        name: '',
        text: '寝ている間、玄関の方から微かに声が聞こえてきた。',
        wifeFace: 'hidden',
        sonFace: 'hidden',
        background: 'entranceE',
        dayText: 'day',
    },
    {
        name: '??',
        text: '「これを持っておけば間違いありません！必ず神のお導きを、、」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '宗教の勧誘だろうか？',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '目が覚めた。時計を見るともう夕方のようだ。',
        wifeFace: 'hidden',
        sonFace: 'hidden',
        background: 'room',
        bgm: 'main',
    },
    {
        name: 'ゆみこ',
        text: '「おはよう。なかなか目を覚さないから心配したのよ。」',
        wifeFace: 'normal',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'どうやら昨日よりもさらに起きるのが遅かったらしい。<br>体が重い。お腹に強い痛みを感じる。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '今日は特に病気の具合が悪いようだ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '仕方ないのでゆみこに病院の予約を頼むと、<br>ゆみこは部屋を出て、しばらくしてまた戻ってきた。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「ごめんなさい。病院、明後日じゃないと予約取れなかった。」<br>「もう少し頑張れる？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「うん。今日は安静にするよ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'なんだか少し違和感もあるが、今日は頭が回らない。<br>ひとまず、ゆみこに判断任せることにしよう。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「それじゃあ、何か食べるものを用意してくるね！」',
        wifeFace: 'smile',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'いつも通りの会話の後、<br>ゆみこは料理を作りに、部屋を後にした。',
        wifeFace: 'hidden',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'ゆみこは本当に優しい。<br>まったく、良い嫁をもった。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「あ！！起きたんだ！」',
        wifeFace: 'stay',
        sonFace: 'normal',
    },
    {
        name: '',
        text: '息子のゆうたが部屋にやってきた。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「ねえねえ！何か欲しいものはある？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'メモ用紙と鉛筆を手に持っている。<br>どうやら頼んだものを持ってきてくれるようだ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'なんて優しい子なんだ！',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '不思議と最近ゆみこに似てきている。<br>成長期の子供は目を離した隙に別人になるってのは本当なんだな。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'さて、今日は音楽を聴くくらいしかできそうにない。<br>何かCDを持ってきてもらおう。',
        wifeFace: 'stay',
        sonFace: 'stay',
        choices: [  // 選択肢
            { text: '大きな失恋のうた', nextScene: 1 },
            { text: 'いつも凡人だった君たちへ', nextScene: 1 },
            { text: '鳥取フルハウス', nextScene: 1 },
        ],
    },
    {
        name: 'あなた',
        text: '「それじゃあ &nbsp ${lastChoiceText} &nbsp がほしいな！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「わかった！ &nbsp ${lastChoiceText} &nbsp だね！」<br>「間違えないようメモしておくね！」',
        wifeFace: 'stay',
        sonFace: 'smile',
    },
    {
        name: '',
        text: 'そう言って部屋を出た後、ゆうたはすぐに<br>${lastChoiceText} &nbsp を持って戻ってきてくれた。',
        wifeFace: 'stay',
        sonFace: 'normal',
    },
    {
        name: 'あなた',
        text: '「ありがとう！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「うん！じゃあまたね！」',
        wifeFace: 'stay',
        sonFace: 'smile',
    },
    {
        name: '',
        text: 'そう言ってゆうたは部屋を出ていった。<br>なんだか少し元気をもらえた気がする。',
        wifeFace: 'stay',
        sonFace: 'hidden',
    },
    {
        name: 'ゆみこ',
        text: '「ご飯できたよー」',
        wifeFace: 'normal',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'しばらくすると、ゆみこが料理を持ってきてくれた。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「今日も最高に美味しいよ！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「褒めすぎだってー」',
        wifeFace: 'smile',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「でも、ありがとう！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '食べ終わった。最高だ。<br>しかしまた薬っぽい味がした。今日は特に調子が悪いしそのせいだろう。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「ねえ、庭を見に行かない？」',
        wifeFace: 'normal',
        sonFace: 'stay',
    },
];
// 4日目庭パート
export const scenesPart4_2 = [
    {
        name: '',
        text: 'ゆみこと俺は庭へ移動した。すると玄関には見慣れない壺があった。<br>新しく買ったのだろうか？',
        wifeFace: 'hidden',
        sonFace: 'stay',
        wheel: 'yellow4',
        background: 'tsubomi',
    },
    {
        name: '',
        text: 'この庭にはたくさんの思い出がある。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「ねえ、うちにある漫画の主人公ってなんでみんな鈍感なの？」',
        wifeFace: 'stay',
        sonFace: 'normal',
        background: 'tsubomi',
        bgm: 'past',
    },
    {
        name: 'あなた',
        text: '「えー、なんでだろうねー？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「なんでヒロインは胸が大きいキャラばかりなの？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「な、なんでだろうねー？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「お母さんはこんな大きくないよね？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ちょ、ちょっと待て！ゆうた、それ以上はやめような？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'ゆみこが庭にやってきた。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「大丈夫？少し顔色悪いみたいだけど。」',
        wifeFace: 'surprised',
        sonFace: 'hidden',
    },
    {
        name: 'あなた',
        text: '「へ、平気だよ！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「たぶん運動不足で体が安定しないだけだから。」<br>「この通り全然余裕で動け、、」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'ﾊﾞﾀｯ',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「え？大丈夫？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「ゆうた、どうしよう？返事しない！！」',
        wifeFace: 'rushing',
        sonFace: 'stay',
    },
    {
        name: 'ゆみこ',
        text: '「落ち着いて！とりあえず救急車を呼ぼう！」',
        wifeFace: 'hidden',
        sonFace: 'normal',
    },
    {
        name: '',
        text: 'そうだ、確かこの庭で倒れて、俺は病院に運ばれたんだった。',
        wifeFace: 'hidden',
        sonFace: 'hidden',
        background: 'tsubomi',
        bgm: 'main',
    },
    {
        name: '',
        text: 'ダメだ。調子が悪いせいか暗いことばかり考えてしまう。<br>今日はもう休もう。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '俺は部屋に戻り、眠りについた。',
        wifeFace: 'hidden',
        sonFace: 'hidden',
        background: 'black',
        bgm: 'stop',
    },
];