// 6日目玄関パート（END分岐）
export const scenesPart6_2_3 = [
    {
        name: '',
        text: 'そうだ、一度この家を離れよう。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '今のゆみこは様子がおかしい。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'なんとかしなきゃいけないが、今の俺じゃ無理だ。<br>暴走したときに手に負えなくなってしまう。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'あまり気は進まないが、ゆみこの実家を頼るのがいいだろう。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'こういう時はきっと良識ある大人の力を借りるのが最善だ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'そう考え、俺は玄関に向かった。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '玄関に行くと、ゆうたがいた。',
        wifeFace: 'stay',
        sonFace: 'stay',
        background: 'entranceN',
    },
    {
        name: 'ゆうた',
        text: '「お母さんを助けるんでしょ？」<br>「僕も連れて行って！」',
        wifeFace: 'stay',
        sonFace: 'normal',
        position: 'son',
    },
    {
        name: '',
        text: 'ゆうたも察しがついているらしい。<br>賢い子だ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'だが、ゆみこの実家にゆうたは連れていけない。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ダメだ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「どうして？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「僕、あの約束覚えてるんだよ！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「どんなことがあっても、お母さんを大切にしろって。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「だから、僕がお母さんを助けるんだ！」',
        wifeFace: 'stay',
        sonFace: 'resolve',
    },
    {
        name: '',
        text: 'ゆうたは覚悟に満ちた表情をしている。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'でも、ダメだ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ゆうた、今から行くのはゆみこの実家なんだ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ゆうたはおじいさんに会ったことがないだろ？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「うん」',
        wifeFace: 'stay',
        sonFace: 'normal',
    },
    {
        name: '',
        text: '「……」',
        wifeFace: 'stay',
        sonFace: 'stay',
        choices: [  // 選択肢
            { text: '真実を話す', nextScene: 1 },
        ],
    },
    {
        name: 'あなた',
        text: '「実はな、これまで黙ってたけど、」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ゆうたは、俺とゆみこの本当の子どもじゃないんだ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ゆうたは覚えてないかもだけど、3歳のときに孤児院で引き取ったんだよ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「知ってたよ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「ちょっとだけど、孤児院にいた頃の記憶あるんだ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「それに、僕にはお父さんがいないじゃん？」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「うちが他の家族と違うのもわかってた。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「そっか、バレてたのか。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「でも、ここからが本題なんだ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
        mainFace: 'resolve',
        position: 'main',
        bgm: 'ending',
    },
    {
        name: 'あなた',
        text: '「ゆみこの実家は裕福なんだよ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「けど、俺は元々孤児だし、当時は不良で、性別も女だ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「だから、ゆみこの両親は俺たちの結婚に反対してた。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「それでも俺が強引にゆみこを連れ出したから、<br>ほとんど勘当されたような状態なんだ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ゆうたのことも、ゆみこの両親には伝えてない。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「だから、話をややこしくしないよう、今回は俺1人で行くよ」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「それに、ゆうたはゆみこのそばにいてやってほしいんだ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「今のゆみこを一人にするのは心配だから。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「こればっかりは、ゆうたにしか任せられない。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「頼めるか？」',
        wifeFace: 'stay',
        sonFace: 'stay',
        choices: [  // 選択肢
            { text: '「うん！わかった！」', nextScene: ['6_2_3', '6_2_3_1'] },
            { text: 'それでも強引についていく', nextScene: ['6_2_3', '6_2_3_2'] },
        ],
    },
];
// 6日目留守番パート（BAD END③ルート）
export const scenesPart6_2_3_1 = [
    {
        name: 'ゆうた',
        text: '「わかったよ。」',
        wifeFace: 'hidden',
        sonFace: 'normal',
        mainFace: 'hidden'
    },
    {
        name: 'ゆうた',
        text: '「でも、これだけは忘れないで」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「僕にとっては2人とも大切なお母さんなんだよ。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「必ず無事に帰ってきてね！」',
        wifeFace: 'stay',
        sonFace: 'smile',
    },
    {
        name: 'あなた',
        text: '「ありがとう！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ゆうた、ゆみこのことは任せた！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「うん！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'しばらく経った。',
        wifeFace: 'stay',
        sonFace: 'hidden',
        bgm: 'stop',
    },
    {
        name: 'ゆみこ',
        text: '「ゆうた、どうして一人で行かせちゃったの？」<br>「あの人は重い病気なのよ！」',
        wifeFace: 'rushing',
        sonFace: 'stay',
        bgm: 'serious',
    },
    {
        name: '',
        text: '思った通り、ゆみこお母さんは取り乱した。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「大丈夫！」<br>「きっと帰ってくるから、信じて待っていよう！」',
        wifeFace: 'stay',
        sonFace: 'resolve',
    },
    {
        name: '',
        text: 'ゆみこお母さんを落ち着かせるために、僕は何度もそう言い聞かせた。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'ある程度落ち着いた後、<br>気疲れしたのかお母さんはそのまま眠ってしまった。',
        wifeFace: 'hidden',
        sonFace: 'hidden',
        background: 'black',
        bgm: 'stop',
        nextScene: ['6_2_3_1', '7_3'],
    },
];
// 6日目追従パート（TRUE ENDルート）
export const scenesPart6_2_3_2 = [
    {
        name: 'ゆうた',
        text: '「それでもいくよ！」',
        wifeFace: 'hidden',
        sonFace: 'resolve',
        mainFace: 'hidden'
    },
    {
        name: 'ゆうた',
        text: '「そんな病気の状態で、一人にはできない。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「だって、僕の」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「もう一人の大切なお母さんだから！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ゆうた、」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'ゆうたの目は力強かった。<br>俺はその眼差しに昔の自分と通じる何かを感じた。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '血の繋がりがないと知ってなお、<br>ゆみこのために、俺のために、ここまで強くあれるのか。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'ゆうたは、本当に、',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「立派に、育ったな。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'ゆうた',
        text: '「うん、2人の息子だから。」',
        wifeFace: 'stay',
        sonFace: 'smile',
    },
    {
        name: 'あなた',
        text: '「ゆうた、ありがとう！一緒に行こう！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「一緒にゆみこを助けよう！」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '熱い抱擁を交わし、俺たちは家を出た。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '家を出てしばらくして、',
        wifeFace: 'stay',
        sonFace: 'hidden',
        background: 'black',
        bgm: 'stop',
    },
    {
        name: '',
        text: '俺は倒れた。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '体力の限界だったのだろう。<br>倒れたとき、俺はその場で、死が近いことを悟った。',
        wifeFace: 'stay',
        sonFace: 'stay',
        background: 'endB3',
    },
    {
        name: '',
        text: 'しかし、不思議と不安はなかった。',
        wifeFace: 'stay',
        sonFace: 'stay',
        bgm: 'ending',
    },
    {
        name: '',
        text: '自分がゆみこを助けなきゃいけないという思いに<br>ついさっきまで駆られていたはずなのに。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'おそらく、ゆうたの覚悟を見たからだろう。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'ゆみこを助けなきゃいけないという思いは、俺が死んでも受け継がれる。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '少々無責任な気もするが、ゆうたはきっとそれすらも背負ってくれる。<br>そんな気がした。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: 'そう思えるほどの強さをゆうたの中に見たのだ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '息子に全部任せてこの世をさるなんて、俺は本当にダメな親だ。',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「ゆうた、ごめんな。」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: 'あなた',
        text: '「あとは、任せた」',
        wifeFace: 'stay',
        sonFace: 'stay',
    },
    {
        name: '',
        text: '俺は意識を失った。',
        wifeFace: 'stay',
        sonFace: 'stay',
        background: 'black',
        bgm: 'stop',
        nextScene: ['6_2_3_2', '7_4'],
    },
];